### ISSUE TITLE
Installing Jminer on ubuntu, launch fails with CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by Tadasu85** [de-luxe/burstcoin-jminer#30]
I am running ubuntu 16.04 and attempting to get jminer up and going, I have already configed my props file and pathed the plot files but when attempting to run jminer from command line with ./run.sh I get the following TB:

Exception in thread "readerPool-1" org.jocl.CLException: CL_OUT_OF_RESOURCES
	at org.jocl.CL.checkResult(CL.java:808)
	at org.jocl.CL.clEnqueueNDRangeKernel(CL.java:20823)
	at burstcoin.jminer.core.checker.util.OCLChecker.findLowest(OCLChecker.java:223)
	at burstcoin.jminer.core.checker.task.OCLCheckerTask.run(OCLCheckerTask.java:71)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at burstcoin.jminer.core.checker.Checker.handleMessage(Checker.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:350)
	at burstcoin.jminer.core.reader.task.ReaderLoadDriveTask.load(ReaderLoadDriveTask.java:140)
	at burstcoin.jminer.core.reader.task.ReaderLoadDriveTask.run(ReaderLoadDriveTask.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Any assistance with this issue would be greatly appreciated.

**Comment by Tadasu85** [comment]
I am a dippy doo, if you run into this issue please verify you defined your platform and device in props like so :    

-----------------------------------------------------------------------------------
# - OpenCL -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------------
# The miner uses openCL for most of the mining calculations, ensure it is setup correctly.
# Instructions can be found e.g. here (thanks cryo):
# https://github.com/bhamon/gpuPlotGenerator/blob/master/README.md
# You could also use that instruction to find your platformId and deviceId if needed.
#
# platformId     - id of openCL platform on your system. one platform may have multiple
# (default:0)      devices, the miner currently uses just one (in general not the bottleneck)
#
# deviceId       - specifies the device used by OCLCecker, can be your first GPU,
# (default:0)      in most cases it will not be 100% used. (depends on capacity)
# -----------------------------------------------------------------------------------
platformId=1
deviceId=0
