### ISSUE TITLE
Errors with Umbuntu 17.10 - Ryzen 5 CPU - not starting

### ISSUE THREAD

**Issue by jrejrdco** [de-luxe/burstcoin-jminer#51]
./run.sh
22:07:52.380 [main] INFO burstcoin.jminer.JMinerApplication - Starting the engines ... please wait!
2018-01-17 22:07:53.140  INFO 26252 --- [           main] b.jminer.core.checker.util.OCLChecker    : -------------------------------------------------------
2018-01-17 22:07:53.142  INFO 26252 --- [           main] b.jminer.core.checker.util.OCLChecker    : List of system openCL platforms and devices (* = used for mining)
2018-01-17 22:07:53.142  INFO 26252 --- [           main] b.jminer.core.checker.util.OCLChecker    : 
2018-01-17 22:07:53.143  WARN 26252 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is org.jocl.CLException: CL_PLATFORM_NOT_FOUND_KHR
2018-01-17 22:07:53.153 ERROR 26252 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is org.jocl.CLException: CL_PLATFORM_NOT_FOUND_KHR
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at burstcoin.jminer.JMinerApplication.main(JMinerApplication.java:68) [classes!/:0.4.11-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [burstcoin-jminer-0.4.11-SNAPSHOT.jar:0.4.11-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [burstcoin-jminer-0.4.11-SNAPSHOT.jar:0.4.11-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [burstcoin-jminer-0.4.11-SNAPSHOT.jar:0.4.11-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [burstcoin-jminer-0.4.11-SNAPSHOT.jar:0.4.11-SNAPSHOT]
Caused by: org.jocl.CLException: CL_PLATFORM_NOT_FOUND_KHR
	at org.jocl.CL.checkResult(CL.java:808) ~[jocl-2.0.0.jar!/:na]
	at org.jocl.CL.clGetPlatformIDs(CL.java:2173) ~[jocl-2.0.0.jar!/:na]
	at burstcoin.jminer.core.checker.util.OCLChecker.initChecker(OCLChecker.java:88) ~[classes!/:0.4.11-SNAPSHOT]
	at burstcoin.jminer.core.checker.util.OCLChecker.postConstruct(OCLChecker.java:78) ~[classes!/:0.4.11-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	... 23 common frames omitted

**Comment by de-luxe** [comment]
@jrejrdco Seams you have no openCL drivers installed ... so no platform/device was detected ... check the links below ...
http://support.amd.com/en-us/kb-articles/Pages/OpenCL2-Driver.aspx
https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk
