### ISSUE TITLE
Jminer crash after last Win10 update

### ISSUE THREAD

**Issue by willieroden** [de-luxe/burstcoin-jminer#65]
Greetings,
I had Jminer humming along without issues and a couple of days ago Win10 did an update and now it pukes when I try to run it.  I didn't change any settings for jminer  - so either OpenCL puked, Java puked, or something in Win10 update is causing an issue.

Java is 1.8.0_161-b12
OpenCl is in current Nvidia driver - 391.35
     I haven't updated Nvidia to 397.64 yet as I wanted this fixed first.....

________________________________________________________________________________________________

D:\jminer>java -jar -d64 -XX:+UseG1GC burstcoin-jminer-0.4.12-RELEASE.jar
07:32:01.905 [main] INFO burstcoin.jminer.JMinerApplication - Starting the engines ... please wait!
Could not load OpenCL.dll, error 126
2018-05-20 07:32:02.826  WARN 14516 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'checker' defined in URL [jar:file:/D:/jminer/burstcoin-jminer-0.4.12-RELEASE.jar!/BOOT-INF/classes!/burstcoin/jminer/core/checker/Checker.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
2018-05-20 07:32:02.840 ERROR 14516 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'checker' defined in URL [jar:file:/D:/jminer/burstcoin-jminer-0.4.12-RELEASE.jar!/BOOT-INF/classes!/burstcoin/jminer/core/checker/Checker.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at burstcoin.jminer.JMinerApplication.main(JMinerApplication.java:87) [classes!/:0.4.12-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [burstcoin-jminer-0.4.12-RELEASE.jar:0.4.12-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [burstcoin-jminer-0.4.12-RELEASE.jar:0.4.12-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [burstcoin-jminer-0.4.12-RELEASE.jar:0.4.12-RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [burstcoin-jminer-0.4.12-RELEASE.jar:0.4.12-RELEASE]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        ... 24 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
        at org.jocl.LibInitializer.initNativeLibrary(LibInitializer.java:74) ~[jocl-2.0.0.jar!/:na]
        at org.jocl.CL.loadNativeLibrary(CL.java:66) ~[jocl-2.0.0.jar!/:na]
        at org.jocl.CL.<clinit>(CL.java:51) ~[jocl-2.0.0.jar!/:na]
        at org.jocl.utils.Platforms.getPlatforms(Platforms.java:51) ~[classes!/:0.4.12-RELEASE]
        at burstcoin.jminer.core.checker.util.OCLChecker.check(OCLChecker.java:153) ~[classes!/:0.4.12-RELEASE]
        at burstcoin.jminer.core.checker.util.OCLChecker.initChecker(OCLChecker.java:83) ~[classes!/:0.4.12-RELEASE]
        at burstcoin.jminer.core.checker.util.OCLChecker.postConstruct(OCLChecker.java:78) ~[classes!/:0.4.12-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:369) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:312) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        ... 37 common frames omitted

**Comment by de-luxe** [comment]
@willieroden there is something wrong with your gpu driver, try to reinstall. if that does not help, ensure platformId and deviceId are set correctly.
https://www.cnet.com/forums/discussions/graphic-card-not-working-after-windows-10-update/

**Comment by willieroden** [comment]
Thank you - I guess Nvidia puked with the update.  Reinstalled video drivers and all is well.

Love your product.  BTW, should I upgrade from 0.4 to 0.5 yet?  Or wait for a couple of more releases since 0.4 is stable and not causing any issues.....

**Comment by de-luxe** [comment]
@willieroden you need to update before block 502000 ... or poc1 plotfiles will get no more valid deadlines ... i consider 0.5.x version to be as stable as previous versions. Would also enable you to start converting your plotfiles to poc2.
