### ISSUE TITLE
jminer crashes if a plot file is actively being plotted

### ISSUE THREAD

**Issue by twig123** [de-luxe/burstcoin-jminer#72]
Using TurboPlotter 9000, it creates files such as this while it is actively plotting:
11111111111111111111_45385088_29929472.plotting

jminer attempts to read this file, then dies in a fire and completely crashes:

```
17:53:16.677    -       Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reader': Invocation of init method failed; nested exception is java.lang.NumberFormatException: For input string: "29929472.plotting"
17:53:16.692    -       Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reader': Invocation of init method failed; nested exception is java.lang.NumberFormatException: For input string: "29929472.plotting"
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
        at burstcoin.jminer.JMinerApplication.main(JMinerApplication.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NumberFormatException: For input string: "29929472.plotting"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.valueOf(Unknown Source)
        at burstcoin.jminer.core.reader.data.PlotFile.<init>(PlotFile.java:65)
        at burstcoin.jminer.core.reader.data.PlotDrive.<init>(PlotDrive.java:53)
        at burstcoin.jminer.core.reader.data.Plots.<init>(Plots.java:63)
        at burstcoin.jminer.core.reader.Reader.getPlots(Reader.java:252)
        at burstcoin.jminer.core.reader.Reader.postConstruct(Reader.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
        ... 23 common frames omitted
```

**Comment by de-luxe** [comment]
@twig123 Thanks for reporting ... for now, just plot to a temp dir, thats not known to jminer. And move the plotfile if finished. The filename '11111111111111111111_45385088_29929472.plotting' can indeed not be understood by jminer,(without that **.plotting** ) it would be no issue i guess ... i will harden it in a future version.

**Comment by sicksvt** [comment]
I ran into the same error while plotting with TurboPlotter and worked around it by adding the following at Line 53 in PlotDrive.java. 

`if(path.toString().endsWith(".plotting")) {
        continue;
}`

**Comment by de-luxe** [comment]
@sicksvt Guess it is no problem to mine a plotflie while it is plotting, i will add a fix that simply removes '.whatever' ... swizzling, plotting ... whatever.

**Comment by sicksvt** [comment]
Mining on a file that is being plotted doesn't cause any problems for me (tested with latest XPlotter and Jminer).

I don't think you can simply remove the .plotting extension because TurboPlotter will have the file handle open, and even if it doesn't at the time, it will expect to write to that file name (with .plotting) when it does its next round of writes. 

Instead, I think you either have to ignore .plotting files, or just specifically look for .plotting files and add them to the path list and treat them as poc2.  At some point though plotting will finish and the plotter will rename the file, so jminer will need to enable scanPathsEveryRound while the path list contains .plotting files, then revert to whatever scanPathsEveryRound is set to in the properties file once there are no more .plotting files in the paths list.

**Comment by de-luxe** [comment]
@sicksvt thx for your feedback, guess you got me wrong ... jminer will not change the name of the file for real, just internal. But you are right, without enabled scanPathsEveryRound, once a file is plotted, jminer will not find the file anymore ... good point.
