### ISSUE TITLE
nVidia OpenCL fails on 'OCLCheck' with CL_BUILD_PROGRAM_FAILURE (Windows 10 1809 update related?)

### ISSUE THREAD

**Issue by systemofapwne** [de-luxe/burstcoin-jminer#79]
After updating to the latest Windows 10 major (1809), officially release a few days ago, JMiner fails to work with nVidia cards (but perfectly works on Intel iGPU). But I have to admit that I also update the nVidia driver simultanously. Nevertheless, JMiner fails on OCLCheck

> 22:05:04.709 [main] INFO burstcoin.jminer.JMinerApplication - Starting the engines ... please wait!
> 22:05:05.509 -------------------------------------------------------
> 22:05:05.510 List of system openCL platforms and devices (* = used for mining)
> 22:05:05.510
> 22:05:05.513  * PLATFORM-[1] NVIDIA CUDA - (OpenCL 1.2 CUDA 10.0.132)
> 22:05:05.514  *   DEVICE-[0] GeForce GTX 980 Ti (6GB) - NVIDIA Corporation (OpenCL 1.2 CUDA | '417.71')
> 22:05:05.515  *          [0] work group size: '1024', computing units: '22', available 'true'
> 22:05:05.611 Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'checker' defined in URL [jar:file:/D:/Tools/Burst%20Wallet/jminer/burstcoin-jminer-0.5.3-SNAPSHOT.jar!/BOOT-INF/classes!/burstcoin/jminer/core/checker/Checker.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
> Build log for device 0:
> 
> 
> 22:05:05.620 Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'checker' defined in URL [jar:file:/D:/Tools/Burst%20Wallet/jminer/burstcoin-jminer-0.5.3-SNAPSHOT.jar!/BOOT-INF/classes!/burstcoin/jminer/core/checker/Checker.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
> Build log for device 0:
> 
> 
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732)
>         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1276)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1133)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
>         at burstcoin.jminer.JMinerApplication.main(JMinerApplication.java:87)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OCLChecker': Invocation of init method failed; nested exception is org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
> Build log for device 0:
> 
> 
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
>         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
>         ... 24 common frames omitted
> Caused by: org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
> Build log for device 0:
> 
> 
>         at org.jocl.CL.clBuildProgram(CL.java:11256)
>         at burstcoin.jminer.core.checker.util.OCLChecker.initChecker(OCLChecker.java:128)
>         at burstcoin.jminer.core.checker.util.OCLChecker.postConstruct(OCLChecker.java:78)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
>         ... 37 common frames omitted

Reinstalling the driver or even installing the CUDA SDK didn't resolve the issue.

**Comment by de-luxe** [comment]
@systemofapwne Thanks for reporting. There is currently nothing i could suggest beside from try to use previous nvidea driver again. I will update jminer libs and provide a new release within the next days, maybe that solves your issues.

**Comment by de-luxe** [comment]
@systemofapwne Feel free to try this build, it is using latest jocl.org lib ... https://www.dropbox.com/s/w35cvfeqlufn8e6/burstcoin-jminer-0.5.4-SNAPSHOT.zip?dl=0

**Comment by systemofapwne** [comment]
It unfortunately did not fix the issue. I will try an older nVidia driver later the next days.

**Comment by de-luxe** [comment]
Too bad, thanks for testing anyway ... i remember there were issues with drivers earlier, doesn't mean i'm sure thats the issue.
